Correct typo

diff --git a/host/farm22-hgi01/bin/gsbServer b/host/farm22-hgi01/bin/gsbServer
--- a/host/farm22-hgi01/bin/gsbServer
+++ b/host/farm22-hgi01/bin/gsbServer
@@ -63,7 +63,7 @@ stop() {
 	if [ -e "$PIDFILE" ]; then
 		declare PID="$(cat "$PIDFILE")";
 		ps -P "$PID" &> /dev/null && {
-			kill "$PID" && echo "GSB Stopped" || echo "GSB  could not be stopped";
+			kill "$PID" && echo "GSB Stopped" || echo "GSB could not be stopped";
 
 			exit 0;
 		}
