Declawed rm

diff --git a/farm/farm5/bin/rm b/farm/farm5/bin/rm
--- a/farm/farm5/bin/rm
+++ b/farm/farm5/bin/rm
@@ -1,7 +1,51 @@
 #!/usr/bin/env bash
 
-# Safe rm
+# Declawed rm
 # Christopher Harrison <ch12@sanger.ac.uk>
 
-# TODO
-exec rm "$@"
+set -eu
+
+declare -a OPTIONS=()
+declare -a FILES=()
+declare -i IN_FILES=0
+
+# Iterate through the provided arguments and
+# silo them into either options or files
+while (( $# )); do
+  case "$1" in
+    "--")
+      if (( IN_FILES ));
+        then FILES+=("$1")
+        else IN_FILES=1
+      fi
+      ;;
+
+    "--"?* | "-"?*)
+      if (( IN_FILES ));
+        then FILES+=("$1")
+        else OPTIONS+=("$1")
+      fi
+      ;;
+
+    *)
+      IN_FILES=1
+      FILES+=("$1")
+      ;;
+  esac
+
+  shift
+done
+
+# Fail if no files are specified
+if ! (( ${#FILES[@]} )); then
+  >&2 echo "$(tput setaf 1)No files provided!$(tput sgr0)"
+  exit 1
+fi
+
+# Append -Iv to the options, with the option separator
+OPTIONS+=("-Iv" "--")
+
+# Output and execute
+declare -a EXEC=("rm" "${OPTIONS[@]}" "${FILES[@]}")
+>&2 echo "${EXEC[*]}"
+exec "${EXEC[@]}"
