Rewrote ibackupServer script, to allow more functions + watchfofns

diff --git a/host/farm22-ibackup01/bin/ibackupServer b/host/farm22-ibackup01/bin/ibackupServer
--- a/host/farm22-ibackup01/bin/ibackupServer
+++ b/host/farm22-ibackup01/bin/ibackupServer
@@ -1,35 +1,29 @@
 #!/bin/bash
 
-if [ "$(hostname)" != "farm22-ibackup01" ]; then
-	echo "This script should only be run on farm22-ibackup01!" >&2;
-
-	exit 1;
-fi;
-
-declare PIDFILE="/nfs/hgi/wr/lsf/.wr_production/pid"
-
-ps -P "$(cat "$PIDFILE" 2>/dev/null)" &> /dev/null || {
-	export WR_CONFIG_DIR=/nfs/hgi/wr/lsf;
-	/software/hgi/installs/wr/wr manager start;
-}
-
-
-declare BASE="/nfs/hgi/ibackup/daemon";
-PIDFILE="$BASE/pid";
-
-if [ -e "$PIDFILE" ]; then
-	ps -P "$(cat "$PIDFILE" 2>/dev/null)" &> /dev/null && {
-		echo "ibackup Already Running";
-
-		exit 0;
-	}
-fi;
-
-echo "Starting ibackup service...";
+export WR_CONFIG_DIR=/nfs/hgi/wr/lsf
+declare EXE="$(realpath /software/hgi/installs/ibackup/ibackup)";
+declare DAEMONIZE="/software/hgi/installs/daemonize/daemonize";
+declare BASE="/nfs/hgi/ibackup/";
+declare -A PIDs=(
+	["server"]="$BASE/daemon/pid"
+	["watchfofns"]="$BASE/watchfofns/pid"
+)
+declare -A LOGs=(
+	["server"]="$BASE/daemon/log"
+	["watchfofns"]="$BASE/watchfofns/log"
+)
+declare -A ERRs=(
+	["server"]="$BASE/daemon/err"
+	["watchfofns"]="$BASE/watchfofns/err"
+)
+declare -A ARGs=(
+	["server"]="-k $BASE/server/key.pem --logfile $BASE/server/log -s ldap-ro.internal.sanger.ac.uk -l 'uid=%s,ou=people,dc=sanger,dc=ac,dc=uk' -r 6h --hardlinks_collection /humgen/ibackup/hardlinks_v2 --statter /software/hgi/installs/ibackup/statter --hung_debug_timeout 20m --queues_avoid cpu-interactive --replica_logging  /local/ibackup/production.db $BASE/server/production.db.bk"
+	["watchfofns"]="--dir /nfs/hgi/ibackup/fofns"
+)
 
 declare SLACK_CREDENTIALS="/nfs/hgi/ibackup/slack-credentials.humgen";
 
-[ -f "$SLACK_CREDENTIALS" ] && . "$SLACK_CREDENTIALS";
+#[ -f "$SLACK_CREDENTIALS" ] && . "$SLACK_CREDENTIALS";
 
 export WR_CONFIG_DIR=/nfs/hgi/wr/lsf;
 export IBACKUP_SERVER_URL='farm22-ibackup01.internal.sanger.ac.uk:4678';
@@ -39,7 +33,99 @@ export IBACKUP_REMOTE_DB_BACKUP_PATH='/humgen/ibackup/db.bk';
 export IBACKUP_CONFIG='/software/hgi/installs/ibackup/.ibackup.config';
 export IRODS_ENVIRONMENT_FILE=/nfs/users/nfs_m/mercury/.irods/irods_environment.humgen.json;
 export PATH="/software/hgi/installs/ibackup:$PATH";
-source /etc/profile.d/lsf.sh
-/software/hgi/installs/daemonize/daemonize -p $BASE/pid -l $BASE/lock -a -e $BASE/err "$(realpath /software/hgi/installs/ibackup/ibackup)" server -k /nfs/hgi/ibackup/server/key.pem --logfile /nfs/hgi/ibackup/server/log -s ldap-ro.internal.sanger.ac.uk -l 'uid=%s,ou=people,dc=sanger,dc=ac,dc=uk' -r 6h --hardlinks_collection /humgen/ibackup/hardlinks_v2 --statter /software/hgi/installs/ibackup/statter --hung_debug_timeout 20m --queues_avoid cpu-interactive --replica_logging  /local/ibackup/production.db /nfs/hgi/ibackup/server/production.db.bk;
+source /etc/profile.d/lsf.sh;
 
-echo "...Done";
+declare WR_PIDFILE="$WR_CONFIG_DIR/.wr_production/pid";
+
+ps -P "$(cat "$WR_PIDFILE" 2>/dev/null)" &> /dev/null || /software/hgi/installs/wr/wr manager start;
+
+printHelp() {
+	if [ -n "${2:-}" ]; then
+		echo -e "$2\n";
+	fi;
+
+	cat <<-HEREDOC
+	IBackup server utility.
+
+	Usage: $0 ${1:-server|watchfofns} start|stop|status|log|logerr
+	HEREDOC
+
+	if [ -n "${2:-}" ]; then
+		exit 1;
+	fi;
+
+	exit 0;
+}
+
+case "${1:-}" in
+"server"|"watchfofns") ;;
+"all")
+	shift;
+
+	for subcommand in ${!PIDs[@]}; do
+		"$0" "$subcommand" "$@";
+	done;
+
+	exit 0;;
+"-h"|"--help")
+	printHelp;;
+*)
+	printHelp "" "Unknown subcommand" >&2;;
+esac;
+
+declare pidFile="${PIDs[$1]}";
+
+isRunning() {
+	local pidFile="$1";
+
+	if [ -f "$pidFile" ]; then
+		declare pid="$(cat "$pidFile")";
+
+		if ps -P "$pid" &> /dev/null; then
+			return 0;
+		fi;
+	fi;
+
+	return 1;
+}
+
+case "${2:-}" in
+"start")
+	if isRunning "$pidFile"; then
+		echo "$1: already started";
+
+		exit 0;
+	fi;;
+"stop")
+	if isRunning "$pidFile"; then
+		kill "$(cat "$pidFile")" && echo "$1 stopped" || {
+			echo "$1: failed to stop" >&2;
+
+			exit 1;
+		}
+
+		exit 0;
+	fi;
+
+	echo "$1: not running";
+
+	exit 0;;
+"status")
+	if isRunning "$pidFile"; then
+		echo "$1: running";
+	else
+		echo "$1: not running";
+	fi;
+
+	exit 0;;
+"log")
+	less +G "${LOGs[$1]}";;
+"logerr")
+	less +G "${ERRs[$1]}";;
+"-h"|"--help")
+	printHelp "$1";;
+*)
+	printHelp "$1" "Unknown action: ${2:-}" >&2;
+esac;
+
+"$DAEMONIZE" -p "$pidFile" -a -e "${ERRs[$1]}" -o "${LOGs[$1]}" "$EXE" "$1" ${ARGs[$1]};
