Added subcommands to gsbServer for easier control.

diff --git a/host/hgi-farm5/bin/gsbServer b/host/hgi-farm5/bin/gsbServer
--- a/host/hgi-farm5/bin/gsbServer
+++ b/host/hgi-farm5/bin/gsbServer
@@ -7,36 +7,84 @@ if [ "$(hostname)" != "hgi-farm5" ]; then
 fi;
 
 export WR_CONFIG_DIR=/nfs/hgi/wr/openstack;
+source /hgi/secrets/mercury-theta-hgi-dev-openrc.sh;
 
-/software/hgi/installs/wr/wr status --deployment production &> /dev/null || {
-	echo "Starting WR in OpenStack...";
-
-	source /hgi/secrets/mercury-theta-hgi-dev-openrc.sh;
-	/software/hgi/installs/wr/wr cloud deploy --manager_flavor m2.medium;
-}
-
+declare WR_PID="";
 declare SOFTPACK_CONFIG=~/.softpack/builder/gsb-config.yml;
-
-if [ ! -f "$SOFTPACK_CONFIG" ]; then
-	echo "SoftPack Builder Configuration File Missing!" >&2;
-
-	exit 1;
-fi;
-
 declare GSBBASE="/nfs/hgi/softpack/gsb/";
 declare PIDFILE="$GSBBASE/pid";
+declare LOGOUT="$GSBBASE/log.out";
+declare LOGERR="$GSBBASE/log.err";
 
-if [ -e "$PIDFILE" ]; then
-	ps -P "$(cat "$PIDFILE")" &> /dev/null && {
-		echo "GSB Already Running";
+start() {
+	if [ ! -f "$SOFTPACK_CONFIG" ]; then
+		echo "SoftPack Builder Configuration File Missing!" >&2;
 
-		exit 0;
+		exit 1;
+	fi;
+
+	/software/hgi/installs/wr/wr status --deployment production &> /dev/null || {
+		echo "Starting WR in OpenStack...";
+
+		/software/hgi/installs/wr/wr cloud deploy --manager_flavor m2.medium;
 	}
-fi;
 
-echo "Starting GSB Server...";
+	if [ -e "$PIDFILE" ]; then
+		ps -P "$(cat "$PIDFILE")" &> /dev/null && {
+			echo "GSB Already Running";
 
-export PATH="/software/hgi/installs/wr/";
-/software/hgi/installs/daemonize/daemonize -p "$PIDFILE" -e "$GSBBASE"/log.err -o "$GSBBASE"/log.out /software/hgi/installs/softpack/gsb-build/gsb server;
+			exit 0;
+		}
+	fi;
 
-echo "...Done";
+	echo "Starting GSB Server...";
+
+	export PATH="/software/hgi/installs/wr/";
+	/software/hgi/installs/daemonize/daemonize -p "$PIDFILE" -a -e "$LOGERR" -o "$LOGOUT" /software/hgi/installs/softpack/gsb-build/gsb server;
+
+	echo "...Done";
+}
+
+stop() {
+	if [ -e "$PIDFILE" ]; then
+		declare PID="$(cat "$PIDFILE")";
+		ps -P "$PID" &> /dev/null && {
+			kill "$PID" && echo "GSB Stopped" || echo "GSB  could not be stopped";
+
+			exit 0;
+		}
+	fi;
+
+	echo "GSB Not Running";
+}
+
+fullstop() {
+	/software/hgi/installs/wr/wr status --deployment production &> /dev/null && {
+		echo "Stopping WR in OpenStack...";
+
+		wr cloud teardown
+
+		echo "...Done";
+	}
+
+	stop;
+}
+
+case "${1:-}" in
+"start") start;;
+"stop") stop;;
+"fullstop") fullstop;;
+"logout") less +G "$LOGOUT";;
+"logerr") less +G "$LOGERR";;
+*)
+	cat <<HEREDOC
+Usage: $0 start|stop|fullstop|logout|logerr
+
+Subcommand
+  start     Start GSB.
+  stop      Stop GSB.
+  fullstop  Stop GSB and WR cloud deployment.
+  logout    Show the standard output log (useful for debugging).
+  logerr    Show the standard error log (useful for debugging).
+HEREDOC
+esac;
